### ISSUE TITLE
Parameter "timeout" needs to be of type "number" but type "undefined"

### ISSUE THREAD

**Issue by Siggi0904** [MiRo1310/ioBroker.alexa-timer-vis#142]
Ich habe heute bei einem Timer folgende Fehlermeldung erhalten.
IOBroker hat den Adapter dann neu gestartet.

Ich kann die Variable aber im Objektbaum nicht finden.
Ist das ein interner Fehler, dass die Variable falsch belegt wurde?

Bisher hatte ich den Fehler nur ganz früher mal in einer älteren Version.
Ich nutze die aktuelle Stable Version 1.0.0 mit Admin 7.1.2, js-controller 6.0.11 und node-js 20.17.0.

```
2024-09-22 12:17:29.927  - error:  alexa-timer-vis.0 (2083956) uncaught exception: Parameter "timeout"  needs to be of type "number" but type "undefined" has been passed
--
2024-09-22 12:17:29.941  - error: alexa-timer-vis.0 (2083956) Error: Parameter "timeout" needs to be of type "number" but type "undefined" has been passed
at Validator.assertNumber  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/validator.js:150:13)
at AlexaTimerVis.setInterval  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:1131:32)
at interval (/opt/iobroker/node_modules/iobroker.alexa-timer-vis/main.js:807:51)
at /opt/iobroker/node_modules/iobroker.alexa-timer-vis/main.js:821:11
at Timeout. (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:1133:34)
at listOnTimeout (node:internal/timers:581:17)
at process.processTimers (node:internal/timers:519:7)
2024-09-22 12:17:29.942  - error: alexa-timer-vis.0 (2083956) Parameter "timeout" needs to be of type "number" but type "undefined" has been passed
2024-09-22 12:17:29.954  - info: alexa-timer-vis.0 (2083956) Apdater shuts down
2024-09-22 12:17:29.955  - info: alexa-timer-vis.0 (2083956) Intervals and timeouts cleared!
2024-09-22 12:17:29.955  - info: alexa-timer-vis.0 (2083956) terminating
2024-09-22 12:17:29.959  - warn: alexa-timer-vis.0 (2083956) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-09-22 12:17:30.461  - info: alexa-timer-vis.0 (2083956) terminating
2024-09-22 12:17:30.639  - error: host.iobroker instance system.adapter.alexa-timer-vis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-09-22 12:17:30.640  - info: host.iobroker Restart adapter system.adapter.alexa-timer-vis.0 because enabled
2024-09-22 12:18:01.529  - info: host.iobroker instance system.adapter.alexa-timer-vis.0 in version "1.0.0" started with pid 2338836
2024-09-22 12:18:03.860  - info:  alexa-timer-vis.0 (2338836) starting. Version 1.0.0 in  /opt/iobroker/node_modules/iobroker.alexa-timer-vis, node: v20.17.0,  js-controller: 6.0.11
2024-09-22 12:18:03.915  - info: alexa-timer-vis.0 (2338836) Alexa State was found
2024-09-22 12:18:03.916  - info:  alexa-timer-vis.0 (2338836) Method "createDevice" is deprecated and  will be removed in js-controller 7, use  "extendObject/setObjectNotExists" instead
2024-09-22 12:18:03.939  - info:  alexa-timer-vis.0 (2338836) Method "createDevice" is deprecated and  will be removed in js-controller 7, use  "extendObject/setObjectNotExists" instead
2024-09-22 12:18:03.950  - info:  alexa-timer-vis.0 (2338836) Method "createDevice" is deprecated and  will be removed in js-controller 7, use  "extendObject/setObjectNotExists" instead
2024-09-22 12:18:03.959  - info:  alexa-timer-vis.0 (2338836) Method "createDevice" is deprecated and  will be removed in js-controller 7, use  "extendObject/setObjectNotExists" instead
```

**Comment by MiRo1310** [comment]
In den nächsten Versionen dürfte das nicht mehr sein. Da habe ich es ja auf Typescript umgestellt. Werde ich aber noch mal prüfen

**Comment by Siggi0904** [comment]
okay. Also kommt der Fehler aus dem intern des Adapters?
Dank dir.

**Comment by MiRo1310** [comment]
Ja
