### ISSUE TITLE
Fehlermeldung ohne Aktion

### ISSUE THREAD

**Issue by Siggi0904** [MiRo1310/ioBroker.alexa-timer-vis#169]
Hallo,

bei mir läuft der folgende Fehler hin und wieder auf, obwohl ich nichts am System oder mit Alexa mache.
Möglicherweise kommt da eine leere Datei zum Adapter.

Kannst du das in einer der nächsten Version einfangen?
Danke.

**Versions:**  
 - Adapter version: 2.0.8
 - JS-Controller version: 7.0.3
 - Admin: 7.1.5
 - Node version: 20.18.1 mit NPM 10.8.2
 - Operating system: Debian 12 in Proxmox-VM

**Log-Eintrag**  
```
2024-12-23 10:53:43.024  - error: alexa-timer-vis.0 (3530) Error in decomposeInputValue: {}
2024-12-23 10:53:43.047  - error:  alexa-timer-vis.0 (3530) "SyntaxError: Unexpected end of input
at  decomposeInputValue  (/opt/iobroker/node_modules/iobroker.alexa-timer-vis/build/lib/decompose-input-value.js:34:35)
at async AlexaTimerVis. (/opt/iobroker/node_modules/iobroker.alexa-timer-vis/build/main.js:130:15)"
2024-12-23 10:53:43.048  - error: alexa-timer-vis.0 (3530) "Unexpected end of input"
```

**Comment by MiRo1310** [comment]
Schaue ich mir an

**Comment by Siggi0904** [comment]
Hi,
warte mal, ich habe gerade gesehen, dass ich erst die 2.0.5 Stable hatte.

Gerade kam die Version 2.0.8 und in 2.0.7 war der Fix drin.

Danke.

**Comment by MiRo1310** [comment]
Dann schließe ich das hier , ansonsten machste wieder ein issue auf.
