### ISSUE TITLE
Crash der Instanz

### ISSUE THREAD

**Issue by rotodt** [MiRo1310/ioBroker.alexa-timer-vis#2]
Crash beim erstellen eines timers von 16 oder 60 Minuten und bei zu langsamer Eingabe von z.B. 25 Minuten:

```
2022-01-31 16:33:20.887  - info: javascript.0 (801) script.js.Global.Alexa_to_command: timer sechzig minuten
--
2022-01-31 16:33:20.891  - info: alexa-timer-vis.0 (7921) Command to control the timer found
2022-01-31 16:33:20.892  - info: alexa-timer-vis.0 (7921) Timer is to be added!
2022-01-31 16:33:20.894  - info: alexa-timer-vis.0 (7921) Voice input: timer sechzig minuten
2022-01-31 16:33:20.897  - error: alexa-timer-vis.0 (7921) uncaught exception: Unexpected token ')'
2022-01-31 16:33:20.906  - error: alexa-timer-vis.0 (7921) SyntaxError: Unexpected token ')'
at AlexaTimerVis. (/opt/iobroker/node_modules/iobroker.alexa-timer-vis/main.js:248:47)
at AlexaTimerVis.emit (events.js:326:22)
at Immediate. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5712:38)
at processImmediate (internal/timers.js:461:21)
2022-01-31 16:33:20.908  - error: alexa-timer-vis.0 (7921) Unexpected token ')'
2022-01-31 16:33:20.957  - info: alexa-timer-vis.0 (7921) Apdater shuts down
2022-01-31 16:33:20.960  - info: alexa-timer-vis.0 (7921) Intervals and timeouts cleared!
2022-01-31 16:33:21.462  - info: alexa-timer-vis.0 (7921) terminating
2022-01-31 16:33:21.463  - warn: alexa-timer-vis.0 (7921) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-01-31 16:33:22.125  - error: host.raspberrypi instance system.adapter.alexa-timer-vis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-01-31 16:33:22.129  - info: host.raspberrypi Restart adapter system.adapter.alexa-timer-vis.0 because enabled
2022-01-31 16:33:52.172  - info: host.raspberrypi instance system.adapter.alexa-timer-vis.0 started with pid 17283
2022-01-31 16:33:53.799  - info:  alexa-timer-vis.0 (17283) starting. Version 0.1.9 in  /opt/iobroker/node_modules/iobroker.alexa-timer-vis, node: v12.22.8,  js-controller: 3.3.22
2022-01-31 16:33:53.880  - info: alexa-timer-vis.0 (17283) Alexa State was found
 





2022-01-31 18:03:07.372  - info: javascript.0 (801) script.js.Global.Alexa_to_command: timer zehn minuten
--
2022-01-31 18:03:07.375  - info: alexa-timer-vis.0 (17283) Command to control the timer found
2022-01-31 18:03:07.375  - info: alexa-timer-vis.0 (17283) Timer is to be added!
2022-01-31 18:03:07.375  - info: alexa-timer-vis.0 (17283) Voice input: timer zehn minuten
2022-01-31 18:03:13.359  - info: javascript.0 (801) script.js.Global.Alexa_to_command: timer fünfzehn minuten
2022-01-31 18:03:13.361  - info: alexa-timer-vis.0 (17283) Command to control the timer found
2022-01-31 18:03:13.362  - info: alexa-timer-vis.0 (17283) Timer is to be added!
2022-01-31 18:03:13.363  - info: alexa-timer-vis.0 (17283) Voice input: timer fünfzehn minuten
2022-01-31 18:03:20.732  - info: javascript.0 (801) script.js.Global.Alexa_to_command: timer zwanzig minuten
2022-01-31 18:03:20.734  - info: alexa-timer-vis.0 (17283) Command to control the timer found
2022-01-31 18:03:20.735  - info: alexa-timer-vis.0 (17283) Timer is to be added!
2022-01-31 18:03:20.735  - info: alexa-timer-vis.0 (17283) Voice input: timer zwanzig minuten
2022-01-31 18:03:28.796  - info: javascript.0 (801) script.js.Global.Alexa_to_command: timer fünf und zwanzig minuten
2022-01-31 18:03:28.800  - info: alexa-timer-vis.0 (17283) Command to control the timer found
2022-01-31 18:03:28.800  - info: alexa-timer-vis.0 (17283) Timer is to be added!
2022-01-31 18:03:28.801  - info: alexa-timer-vis.0 (17283) Voice input: timer fünf und zwanzig minuten
2022-01-31 18:03:28.803  - error: alexa-timer-vis.0 (17283) uncaught exception: Unexpected end of input
2022-01-31 18:03:28.807  - error: alexa-timer-vis.0 (17283) SyntaxError: Unexpected end of input
at AlexaTimerVis. (/opt/iobroker/node_modules/iobroker.alexa-timer-vis/main.js:248:47)
at AlexaTimerVis.emit (events.js:326:22)
at Immediate. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5712:38)
at processImmediate (internal/timers.js:461:21)
2022-01-31 18:03:28.807  - error: alexa-timer-vis.0 (17283) Unexpected end of input
2022-01-31 18:03:28.838  - info: alexa-timer-vis.0 (17283) Apdater shuts down
2022-01-31 18:03:28.843  - info: alexa-timer-vis.0 (17283) Intervals and timeouts cleared!
2022-01-31 18:03:29.344  - info: alexa-timer-vis.0 (17283) terminating
2022-01-31 18:03:29.345  - warn: alexa-timer-vis.0 (17283) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-01-31 18:03:30.033  - error: host.raspberrypi instance system.adapter.alexa-timer-vis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-01-31 18:03:30.038  - info: host.raspberrypi Restart adapter system.adapter.alexa-timer-vis.0 because enabled

**Comment by MiRo1310** [comment]
Es funktioniert jetzt mit den Zahlen 16 und 60

**Comment by rotodt** [comment]
Perfekt! 
Nochmals vielen Dank für den Adapter :-)

**Comment by MiRo1310** [comment]
Kein Problem,, update aber am besten nochmal, nachdem ich das eine gefixed hatte wollte das andere nicht mehr, jetzt sollte aber alles gehen, ansonsten einfach noch mal melden
