### ISSUE TITLE
Fehler beim anlegen eines zweiten Timers

### ISSUE THREAD

**Issue by fornax76-git** [MiRo1310/ioBroker.alexa-timer-vis#3]
Beim anlegen eines zweiten Timers kommt es zu einem Fehler.
Dies tritt dann auf, wenn Alexa fragt, ob sie dem Timer einen Namen geben soll.
Legt man den zweiten Timer direkt mit einem Namen an, tritt der Fehler nicht auf.

`2022-02-01 13:56:52.279 - info: alexa-timer-vis.0 (5350) starting. Version 0.1.9 in /opt/iobroker/node_modules/iobroker.alexa-timer-vis, node: v14.18.3, js-controller: 3.3.22
2022-02-01 13:56:52.359 - info: alexa-timer-vis.0 (5350) Alexa State was found
2022-02-01 13:57:24.053 - info: alexa-timer-vis.0 (5350) Command to control the timer found
2022-02-01 13:57:24.054 - info: alexa-timer-vis.0 (5350) Timer is to be added!
2022-02-01 13:57:24.055 - info: alexa-timer-vis.0 (5350) Voice input: setze einen timer auf fünfzehn minuten
2022-02-01 13:57:40.351 - info: alexa-timer-vis.0 (5350) Command to control the timer found
2022-02-01 13:57:40.355 - info: alexa-timer-vis.0 (5350) Timer is to be added!
2022-02-01 13:57:40.357 - info: alexa-timer-vis.0 (5350) Voice input: setze ein timer auf zwanzig minuten
2022-02-01 13:57:48.945 - info: alexa-timer-vis.0 (5350) Command to control the timer found
2022-02-01 13:57:48.946 - info: alexa-timer-vis.0 (5350) Timer is to be added!
2022-02-01 13:57:48.949 - info: alexa-timer-vis.0 (5350) Voice input: setze ein timer auf zwanzig minuten, nein
2022-02-01 13:57:48.951 - error: alexa-timer-vis.0 (5350) uncaught exception: Unexpected end of input
2022-02-01 13:57:48.955 - error: alexa-timer-vis.0 (5350) SyntaxError: Unexpected end of input
at AlexaTimerVis. (/opt/iobroker/node_modules/iobroker.alexa-timer-vis/main.js:248:47)
at AlexaTimerVis.emit (events.js:412:35)
at Immediate. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5712:38)
at processImmediate (internal/timers.js:464:21)
2022-02-01 13:57:48.956 - error: alexa-timer-vis.0 (5350) Unexpected end of input
2022-02-01 13:57:48.975 - info: alexa-timer-vis.0 (5350) Apdater shuts down
2022-02-01 13:57:48.979 - info: alexa-timer-vis.0 (5350) Intervals and timeouts cleared!
2022-02-01 13:57:49.480 - info: alexa-timer-vis.0 (5350) terminating
2022-02-01 13:57:49.481 - warn: alexa-timer-vis.0 (5350) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-02-01 13:57:50.141 - error: host.ioBroker instance system.adapter.alexa-timer-vis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-02-01 13:58:23.082 - info: alexa-timer-vis.0 (5407) starting. Version 0.1.9 in /opt/iobroker/node_modules/iobroker.alexa-timer-vis, node: v14.18.3, js-controller: 3.3.22
2022-02-01 13:58:23.157 - info: alexa-timer-vis.0 (5407) Alexa State was found`

**Comment by MiRo1310** [comment]
Musste mal ausprobieren ob es so geht.
Wenn du dieses bestätigst das du einen Namen vergeben willst, wird dieses aber nicht in meinem Adapter berücksichtigt, noch nicht sage ich mal. 

Teste mal und sag Bescheid.
Es sollte ab jetzt grundsätzlich nicht mehr vorkommen das der Adapter abstürzt. Es wird nur halt kein Timer gestellt, so ist meine Erwartung.
